= hello-clojurescript.core
== Important links for playing around

- http://localhost:9500/
- https://cljs.info/cheatsheet/
- https://kanaka.github.io/clojurescript/web/synonym.html
- http://www.4clojure.com/
- https://google.github.io/closure-library/api/
- https://cljs.github.io/api/


== ToDos
[] `clj` and `cljc` namespaces 
[] Replace this with Hiccup based HTML generation 
[] Replace this with Garden based CSS generation 


FIXME: Write a one-line description of your library/project.

== Overview

FIXME: Write a paragraph about the library/project and highlight its goals.

== Development

To get an interactive development environment run:

    lein fig:build

This will auto compile and send all changes to the browser without the
need to reload. After the compilation process is complete, you will
get a Browser Connected REPL. An easy way to try it is:

    (js/alert "Am I connected?")

and you should see an alert in the browser window.

To clean all compiled files:

	lein clean

To create a production build run:

	lein clean
	lein fig:min


== License

Copyright © 2019 abhi18av

Distributed under the Eclipse Public License either version 1.0 or (at your option) any later version.
